const users = [
    {
        fname: "morticia",
        lname: "colon",
        password: "3GqrryGN",
        username: "TLoehfelm",
        isAdmin: false,
    },
    {
        fname: "cecelia",
        lname: "lammers",
        password: "3jLQgEAE",
        username: "SMaher",
        isAdmin: false,
    },
    {
        fname: "rich",
        lname: "lehman",
        password: "BF21tABe",
        username: "TWyner",
        isAdmin: false,
    },
    {
        fname: "janelle",
        lname: "mize",
        password: "VqDWfmpG",
        username: "TPrezzavento",
        isAdmin: false,
    },
    {
        fname: "rajesh",
        lname: "kimmel",
        password: "tPZQzCc9",
        username: "WMoudry",
        isAdmin: false,
    },
    {
        fname: "debra",
        lname: "neese",
        password: "8Ew0VOy0",
        username: "JAmacker",
        isAdmin: false,
    },
    {
        fname: "marla",
        lname: "odle",
        password: "npRArmsU",
        username: "ARay",
        isAdmin: false,
    },
    {
        fname: "kingi",
        lname: "flack",
        password: "26SRH7pL",
        username: "SBatson",
        isAdmin: false,
    },
    {
        fname: "luigino",
        lname: "mills",
        password: "TzSEFW6D",
        username: "BBélanger",
        isAdmin: false,
    },
    {
        fname: "lisa",
        lname: "holliday",
        password: "Fzl8TTn6",
        username: "ANajanick",
        isAdmin: false,
    },
    {
        fname: "veneta",
        lname: "walls",
        password: "BCtVrdzM",
        username: "KKostiuk",
        isAdmin: false,
    },
    {
        fname: "roya",
        lname: "silva",
        password: "GOPyaOLy",
        username: "BEfird",
        isAdmin: false,
    },
    {
        fname: "jeff",
        lname: "hovanec",
        password: "RwKv6Jqh",
        username: "NMedina",
        isAdmin: false,
    },
    {
        fname: "evan",
        lname: "fouts",
        password: "AOQH8xCF",
        username: "CBario",
        isAdmin: false,
    },
    {
        fname: "chaiporn",
        lname: "young",
        password: "hrkMBGan",
        username: "PFultz",
        isAdmin: false,
    },
    {
        fname: "marina",
        lname: "evans",
        password: "VyS1eHwj",
        username: "VFilleul",
        isAdmin: false,
    },
    {
        fname: "cori",
        lname: "dehaven",
        password: "vluaorBV",
        username: "EEntinger",
        isAdmin: false,
    },
    {
        fname: "syed",
        lname: "reilly",
        password: "h6yuhcb7",
        username: "NSchaffer",
        isAdmin: false,
    },
    {
        fname: "zachary",
        lname: "tippit",
        password: "7iPqcR4V",
        username: "AChristiansen",
        isAdmin: false,
    },
    {
        fname: "christine",
        lname: "lakritz",
        password: "yyyXfX8u",
        username: "TGranzow",
        isAdmin: false,
    },
    {
        fname: "leticia",
        lname: "lyman",
        password: "Ko6lXmpQ",
        username: "YScribner",
        isAdmin: false,
    },
    {
        fname: "sanjay",
        lname: "wieland",
        password: "AlzahUQl",
        username: "LKirkley",
        isAdmin: false,
    },
    {
        fname: "polina",
        lname: "barnes",
        password: "ruBIxb7I",
        username: "STran",
        isAdmin: false,
    },
    {
        fname: "elsuhaili",
        lname: "cahill",
        password: "KWBGtVOE",
        username: "ALund",
        isAdmin: false,
    },
    {
        fname: "cerelia",
        lname: "vanessen",
        password: "rz9QeObp",
        username: "ABreeland",
        isAdmin: false,
    },
    {
        fname: "cori",
        lname: "kaspar",
        password: "HGZB75kq",
        username: "SGow",
        isAdmin: false,
    },
    {
        fname: "jephter",
        lname: "underwood",
        password: "og1ld2qt",
        username: "DVentura",
        isAdmin: false,
    },
    {
        fname: "janis",
        lname: "anglin",
        password: "mahlGY1M",
        username: "ARipley",
        isAdmin: false,
    },
    {
        fname: "winnie",
        lname: "bommi",
        password: "XaJzer6V",
        username: "SFouts",
        isAdmin: false,
    },
    {
        fname: "yelena",
        lname: "ayers",
        password: "GuljTqqP",
        username: "PShofstahl",
        isAdmin: false,
    },
    {
        fname: "ron",
        lname: "pennell",
        password: "YG55haoR",
        username: "AHeppelmann",
        isAdmin: false,
    },
    {
        fname: "gloria",
        lname: "bartlett",
        password: "FS3CJb9t",
        username: "AJayanti",
        isAdmin: false,
    },
    {
        fname: "staci",
        lname: "bashford",
        password: "GwXswflM",
        username: "DKovach",
        isAdmin: false,
    },
    {
        fname: "tracie",
        lname: "delaura",
        password: "48Jcl8QV",
        username: "TPeck",
        isAdmin: false,
    },
    {
        fname: "birbal",
        lname: "spellicy",
        password: "9475jpPp",
        username: "KLindsay",
        isAdmin: false,
    },
    {
        fname: "yolanda",
        lname: "pollard",
        password: "QJJp2Dty",
        username: "OPeck",
        isAdmin: false,
    },
    {
        fname: "latrese",
        lname: "lang",
        password: "mh9h2bZI",
        username: "EPeters",
        isAdmin: false,
    },
    {
        fname: "cheryl",
        lname: "sapp",
        password: "1F1buAww",
        username: "VBrenner",
        isAdmin: false,
    },
    {
        fname: "evelyn",
        lname: "harkema",
        password: "VtYbkIkv",
        username: "CSchreiner",
        isAdmin: false,
    },
    {
        fname: "karintha",
        lname: "gumatay",
        password: "kL7MhdEs",
        username: "NIbanez",
        isAdmin: false,
    },
    {
        fname: "erich",
        lname: "pomykala",
        password: "FtsuRrGl",
        username: "KCulp",
        isAdmin: false,
    },
    {
        fname: "azra",
        lname: "birnstill",
        password: "nYD95ykA",
        username: "JChapman",
        isAdmin: false,
    },
    {
        fname: "noreen",
        lname: "billanti",
        password: "D3ViQsCj",
        username: "SKhan",
        isAdmin: false,
    },
    {
        fname: "daydria",
        lname: "chenevert",
        password: "jX6W13pa",
        username: "SSchotuen",
        isAdmin: false,
    },
    {
        fname: "nikko",
        lname: "peters",
        password: "FRfw1ZB2",
        username: "JBeringer",
        isAdmin: false,
    },
    {
        fname: "rahul",
        lname: "roos",
        password: "LZ8nAdC0",
        username: "AEverly",
        isAdmin: false,
    },
    {
        fname: "mikel",
        lname: "price",
        password: "hok6VLQ7",
        username: "MCamiling",
        isAdmin: false,
    },
    {
        fname: "lane",
        lname: "darling",
        password: "cATYDQTa",
        username: "VChandrasekahran",
        isAdmin: false,
    },
    {
        fname: "ritalerae",
        lname: "szymanski",
        password: "JF2GY6NJ",
        username: "RDunn",
        isAdmin: false,
    },
    {
        fname: "howard",
        lname: "shapiro",
        password: "cX6JbriU",
        username: "IGrubbs",
        isAdmin: false,
    },
];

var pUsers = users.map((user) => {
    user.fname = user.fname.toLowerCase();
    user.lname = user.lname.toLowerCase();
    return user;
});

var y = JSON.stringify(pUsers);
